apiVersion: apps/v1
kind: Deployment
metadata:
  name: project11-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project11
  template:
    metadata:
      labels:
        app: project11
    spec:
      containers:
      - name: project11
        image: 945714903325.dkr.ecr.us-east-1.amazonaws.com/project11-app:latest
        ports:
        - containerPort: 8080
